### ISSUE TITLE
Model conversion using jax2tf.convert(enable_xla=False) fails on GPU

### ISSUE THREAD

**Issue by dluo96** [jax-ml/jax#11562]
When I run reinforcement learning experiments and create a snapshot (which I can later use to restore the model and use it for inference), I am converting a custom data class (which contains all the necessary info to store a JAX model) to a `tf.Module` using the` jax2tf.convert()` function. 

- ✅ When I run this code on CPU, the snapshotting works without issues.
- 🔴 However, when I run it on GPU, it fails. Specifically, it fails with the error below:

```
  File "/opt/venv/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/opt/venv/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.NotFoundError: Graph execution error:

Detected at node 'XlaDotV2_3' defined at (most recent call last):

    File "/opt/venv/lib/python3.8/site-packages/jax/experimental/jax2tf/jax2tf.py", line 438, in converted_fun
      out_flat = converted_fun_flat_with_custom_gradient(*args_flat)
    File "/opt/venv/lib/python3.8/site-packages/jax/experimental/jax2tf/jax2tf.py", line 431, in converted_fun_flat_with_custom_gradient
      out_with_avals = _interpret_fun(flat_fun, args_flat, args_avals_flat,
    File "/opt/venv/lib/python3.8/site-packages/jax/experimental/jax2tf/jax2tf.py", line 503, in _interpret_fun
      _call_wrapped_with_new_constant_cache(fun, in_vals,
    File "/opt/venv/lib/python3.8/site-packages/jax/experimental/jax2tf/jax2tf.py", line 523, in _call_wrapped_with_new_constant_cache
      fun.call_wrapped(*in_vals)
    File "/opt/venv/lib/python3.8/site-packages/jax/linear_util.py", line 166, in call_wrapped
      ans = self.f(*args, **dict(self.params, **kwargs))
    File "/opt/venv/lib/python3.8/site-packages/jax/experimental/jax2tf/jax2tf.py", line 284, in fun_no_kwargs
      return fun(*args, **kwargs)
    File "/opt/venv/lib/python3.8/site-packages/haiku/_src/multi_transform.py", line 298, in apply_fn
      return f.apply(params, None, *args, **kwargs)
    File "/opt/venv/lib/python3.8/site-packages/haiku/_src/transform.py", line 127, in apply_fn
      out, state = f.apply(params, {}, *args, **kwargs)
    File "/opt/venv/lib/python3.8/site-packages/haiku/_src/transform.py", line 354, in apply_fn
      out = f(*args, **kwargs)
    File "/opt/venv/lib/python3.8/site-packages/haiku/_src/module.py", line 421, in wrapped
      out = f(*args, **kwargs)
    File "/opt/venv/lib/python3.8/site-packages/haiku/_src/module.py", line 271, in run_interceptors
      return bound_method(*args, **kwargs)
    File "/opt/venv/lib/python3.8/site-packages/haiku/_src/module.py", line 421, in wrapped
      out = f(*args, **kwargs)
    File "/opt/venv/lib/python3.8/site-packages/haiku/_src/module.py", line 271, in run_interceptors
      return bound_method(*args, **kwargs)
    File "/opt/venv/lib/python3.8/site-packages/haiku/_src/module.py", line 421, in wrapped
      out = f(*args, **kwargs)
    File "/opt/venv/lib/python3.8/site-packages/haiku/_src/module.py", line 271, in run_interceptors
      return bound_method(*args, **kwargs)
    File "/opt/venv/lib/python3.8/site-packages/haiku/_src/nets/mlp.py", line 113, in __call__
      out = layer(out)
    File "/opt/venv/lib/python3.8/site-packages/haiku/_src/module.py", line 421, in wrapped
      out = f(*args, **kwargs)
    File "/opt/venv/lib/python3.8/site-packages/haiku/_src/module.py", line 271, in run_interceptors
      return bound_method(*args, **kwargs)
    File "/opt/venv/lib/python3.8/site-packages/haiku/_src/basic.py", line 178, in __call__
      out = jnp.dot(inputs, w, precision=precision)
    File "/opt/venv/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
      return fun(*args, **kwargs)
    File "/opt/venv/lib/python3.8/site-packages/jax/_src/api.py", line 447, in cache_miss
      out_flat = xla.xla_call(
    File "/opt/venv/lib/python3.8/site-packages/jax/core.py", line 1711, in bind
      return call_bind(self, fun, *args, **params)
    File "/opt/venv/lib/python3.8/site-packages/jax/core.py", line 1724, in call_bind
      outs = top_trace.process_call(primitive, fun, tracers, params)
    File "/opt/venv/lib/python3.8/site-packages/jax/experimental/jax2tf/jax2tf.py", line 894, in process_call
      vals_out = interpreted_fun.call_wrapped(*vals)
    File "/opt/venv/lib/python3.8/site-packages/jax/linear_util.py", line 166, in call_wrapped
      ans = self.f(*args, **dict(self.params, **kwargs))
    File "/opt/venv/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 2689, in dot
      return lax.dot_general(a, b, (contract_dims, batch_dims), precision)
    File "/opt/venv/lib/python3.8/site-packages/jax/_src/lax/lax.py", line 698, in dot_general
      return dot_general_p.bind(lhs, rhs,
    File "/opt/venv/lib/python3.8/site-packages/jax/core.py", line 288, in bind
      return self.bind_with_trace(find_top_trace(args), args, params)
    File "/opt/venv/lib/python3.8/site-packages/jax/core.py", line 291, in bind_with_trace
      out = trace.process_primitive(self, map(trace.full_raise, args), params)
    File "/opt/venv/lib/python3.8/site-packages/jax/experimental/jax2tf/jax2tf.py", line 839, in process_primitive
      val_out = invoke_impl()
    File "/opt/venv/lib/python3.8/site-packages/jax/experimental/jax2tf/jax2tf.py", line 816, in invoke_impl
      return impl(
    File "/opt/venv/lib/python3.8/site-packages/jax/experimental/jax2tf/jax2tf.py", line 1582, in _dot_general
      res = tfxla.dot_general(
    File "/opt/venv/lib/python3.8/site-packages/tensorflow/compiler/tf2xla/python/xla.py", line 335, in dot_general
      return gen_xla_ops.xla_dot_v2(
    File "/opt/venv/lib/python3.8/site-packages/tensorflow/compiler/tf2xla/ops/gen_xla_ops.py", line 834, in xla_dot_v2
      _, _, _op, _outputs = _op_def_library._apply_op_helper(
Node: 'XlaDotV2_3'
could not find registered platform with id: 0x7fe46b520c14
         [[{{node XlaDotV2_3}}]] [Op:__inference_converted_fun_15300]
```
We see this error even when we use different GPUs. For example, we saw the above error when running the experiments on a machine with Tesla T4 GPU and CUDA 11.4 / cuDNN 8.2.2 / Driver Version: 470.129.06. 

Setting the flag `enable_xla=False` seemed to get around this error, however it led to downstream errors due to some of the JAX operations not being supported when `enable_xla=False` such as `jnp.take_along_axis()`. 

It is a bit tricky to create a minimum reproducible example without including a lot of the source code, so I wanted to first ask if you have seen this or a similar issue before?

**Comment by gnecula** [comment]
This seems to be a TensorFlow problem with the registration of the XlaDotV2 op for GPU. To really fix it, I would need a TF repro, which we can use to get help from TF developers.

As a workaround, it seems that you are executing the result of jax2tf.convert in TF eager mode.
I am curious if the problem persists if you (a) run with TF compilation (`tf.function(f, jit_compile=True)`), or (b) stage to a SavedModel (see examples in the documentation). I am thinking that at least saving to SavedModel will succeed. Then you can reload the model and invoke it from JAX with jax2tf.call_tf, which may not need the XlaDotV2 registration for GPU.

For the repro, try the following program on your GPU machine. 
```
  def test_tf_shape_dot_general(self):
    from tensorflow.compiler.tf2xla.python import xla as tfxla  # type: ignore[import]
    from tensorflow.compiler.xla import xla_data_pb2  # type: ignore[import]
    def f_tf(lhs, rhs):
      dnums_proto = xla_data_pb2.DotDimensionNumbers()
      dnums_proto.lhs_contracting_dimensions.append(1)
      dnums_proto.rhs_contracting_dimensions.append(0)
      precision_config_proto = None
      return tfxla.dot_general(
          lhs,
          rhs,
          dnums_proto,
          precision_config_proto,
          preferred_element_type=tf.float32)

    lhs = np.ones((16, 32), dtype=np.float32)
    rhs = np.ones((32, 4), dtype=np.float32)
    f_tf(lhs, rhs)
```

Note that `tfxla.dot_general` will use the `XlaDotV2` if `preferred_element_type` is not `None`, or if `use_v2=True` is passed to the `dot_general` function. Otherwise it uses `XlaDot`. I'd be curious if the `XlaDot` works but `XlaDotV2` does not.

**Comment by gnecula** [comment]
@rxsang FYI

**Comment by dluo96** [comment]
Thank you for replying so quickly @gnecula! 

**Running with TF compilation**
When I run my script with `tf.function(jax2tf.convert(jax_fn_to_save), autograph=False)` replaced by `tf.function(jax2tf.convert(jax_fn_to_save), jit_compile=True, autograph=False)`, I no longer see the error related to `XlaDotV2`. However, we now see the following error downstream (the code no longer fails at `jax2tf.convert`): 

```
Error executing job with overrides: []
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/opt/venv/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.NotFoundError: could not find registered platform with id: 0x7f34afe13c14 [Op:__inference_converted_fun_1177]

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[reverb/cc/platform/default/server.cc:84] Shutting down replay server
Exception ignored in: <function IteratorResourceDeleter.__del__ at 0x7f3475e17790>
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 570, in __del__
AttributeError: 'NoneType' object has no attribute 'eager_mode'
```
The code now fails on the line `module.forward(**model.dummy_kwargs)` rather than `module.forward = tf.function(jax2tf.convert(jax_fn_to_save), jit_compile=True, autograph=False)` in our code snippet below:

```
def model_to_tf_module(model: ModelToSnapshot) -> tf.Module:
    """Converts a jax based ModelToSnapshot to a tf.Module."""

    def jax_fn_to_save(**kwargs: Dict) -> Any:
        return model.model(model.params, **kwargs)

    module = tf.Module()
    module.forward = tf.function(jax2tf.convert(jax_fn_to_save), jit_compile=True, autograph=False)
    # Traces input to ensure the model has the correct shapes.
    module.forward(**model.dummy_kwargs)

    return module
```
In addition, we cannot afford to disable TF eager mode (e.g. via `tf.compat.v1.disable_eager_execution()`) since it leads to errors in our dependencies, specifically around operations that are only supported in eager mode. 

**Saving to SavedModel**
This would be a more significant change to the codebase, so we were thinking of trying this as a last resort. 

**XlaDot vs XlaDotV2** 
I ran the program you shared on my GPU VM and these were the results:
- ✅ The programs runs successfully when `preferred_element_type=tf.float32` (i.e. not `None`)
- ✅ The programs runs successfully when `preferred_element_type=None`

Thus, based on what you were saying, it seems that the program works with both `XlaDot` and `XlaDotV2`. 

I hope the results of these experiments are helpful! Thanks again for all the help.

**Comment by gnecula** [comment]
I was hoping (and kind of certain) that the program I gave you will fail. I am not thinking that it may have run on the CPU and not on the GPU. Are you sure it ran on the GPU? If you are not sure how to do that I can dust off some code that I use in my tests for this.

**Comment by dluo96** [comment]
Interesting - I have double checked by printing which device the resulting tensor is on, which seems to confirm that the program was run on GPU (the resulting tensor has attribute `device` of `/job:localhost/replica:0/task:0/device:GPU:0` in both runs). I modified your program slightly to see whether the program is running on GPU:
```
def test_tf_shape_dot_general():
    from tensorflow.compiler.tf2xla.python import xla as tfxla  # type: ignore[import]
    from tensorflow.compiler.xla import xla_data_pb2  # type: ignore[import]
    import numpy as np
    import tensorflow as tf
    def f_tf(lhs, rhs):
        dnums_proto = xla_data_pb2.DotDimensionNumbers()
        dnums_proto.lhs_contracting_dimensions.append(1)
        dnums_proto.rhs_contracting_dimensions.append(0)
        precision_config_proto = None
        return tfxla.dot_general(
            lhs,
            rhs,
            dnums_proto,
            precision_config_proto,
            preferred_element_type=None)

    lhs = np.ones((16, 32), dtype=np.float32)
    rhs = np.ones((32, 4), dtype=np.float32)
    t = f_tf(lhs, rhs)
    print(t.device)

test_tf_shape_dot_general()
```
Running this returns the following:
```
2022-07-22 10:21:19.408664: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-22 10:21:19.419082: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-22 10:21:19.419806: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-22 10:21:19.420785: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-07-22 10:21:19.421894: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-22 10:21:19.422695: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-22 10:21:19.423354: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-22 10:21:20.058325: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-22 10:21:20.059013: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-22 10:21:20.059696: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-22 10:21:20.060338: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13795 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5
2022-07-22 10:21:20.329985: I tensorflow/compiler/xla/service/service.cc:170] XLA service 0x564e7b414810 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2022-07-22 10:21:20.330045: I tensorflow/compiler/xla/service/service.cc:178]   StreamExecutor device (0): Tesla T4, Compute Capability 7.5
2022-07-22 10:21:20.339457: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:263] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2022-07-22 10:21:21.195001: I tensorflow/compiler/jit/xla_compilation_cache.cc:478] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
/job:localhost/replica:0/task:0/device:GPU:0
```
When I run the program with `preferred_element_type=tf.float32` instead, the following is returned:
```
2022-07-22 10:22:50.229237: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-22 10:22:50.238714: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-22 10:22:50.239327: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-22 10:22:50.240305: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-07-22 10:22:50.241294: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-22 10:22:50.241910: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-22 10:22:50.242491: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-22 10:22:50.860174: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-22 10:22:50.860949: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-22 10:22:50.861511: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-22 10:22:50.862047: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13795 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5
2022-07-22 10:22:51.127199: I tensorflow/compiler/xla/service/service.cc:170] XLA service 0x559ab8763fa0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2022-07-22 10:22:51.127253: I tensorflow/compiler/xla/service/service.cc:178]   StreamExecutor device (0): Tesla T4, Compute Capability 7.5
2022-07-22 10:22:51.136358: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:263] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2022-07-22 10:22:51.982894: I tensorflow/compiler/jit/xla_compilation_cache.cc:478] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
/job:localhost/replica:0/task:0/device:GPU:0
```

**Comment by marcvanzee** [comment]
@dluo96, in your original post you say:

"Setting the flag enable_xla=False seemed to get around this error, however it led to downstream errors due to some of the JAX operations not being supported when enable_xla=False such as jnp.take_along_axis()."

Maybe you could try running this again? We added more support for jax2tf (enable_xla=False) recently, so it might just work.

If it doesn't work, could you post the full stack trace?

**Comment by gnecula** [comment]
Should we change the subject of this bug to refer to enable_xla=False?

**Comment by gnecula** [comment]
`enable_xla=False` is not supported anymore
