### ISSUE TITLE
UnfilteredStackTrace when using jit, Stack trace doesn't give me enough info to debug issue.

### ISSUE THREAD

**Issue by peterroelants** [jax-ml/jax#15754]
### Description

I have a Python script that runs a sequence of model fits (`run_sample`) in a loop. If I JIT my gradient update step I get the error below after a couple of model fit iterations (each running `run_sample`). However when I run without jitting using `JAX_DISABLE_JIT=True` everything runs fine (but it is slow), I don't see any errors.

The problem is, I can't really figure out from the stack trace below where the exception is coming from. And the exception doesn't appear when disable jitting.
The `ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()` made me think I had some boolean check I was not using correctly. However, I cannot find such a check in my code, and the fact that the code is running fine without JIT compilation makes me think that the error might be coming from JAX.

```python-traceback
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()                                                                           
Traceback (most recent call last):                                                                                                                                                
  File "~/workspace/lcms_polymer_model/./src/scripts/run_all.py", line 260, in <module>                                                                         
    run_all()                                                                                                                                                                     
  File "~/workspace/lcms_polymer_model/./src/scripts/run_all.py", line 100, in run_all                                                                          
    run_sample(                                                                                                                                                                   
  File "~/workspace/lcms_polymer_model/./src/scripts/run_all.py", line 180, in run_sample                                                                       
    loss, params_state, _ = step_func(                                                                                                                                            
  File "~/mambaforge/envs/lcms_polymer_env/lib/python3.10/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback               
    return fun(*args, **kwargs)                                                                                                                                                   
  File "~/mambaforge/envs/lcms_polymer_env/lib/python3.10/site-packages/jax/_src/pjit.py", line 238, in cache_miss                                              
    outs, out_flat, out_tree, args_flat = _python_pjit_helper(                                                                                                                    
  File "~/mambaforge/envs/lcms_polymer_env/lib/python3.10/site-packages/jax/_src/pjit.py", line 180, in _python_pjit_helper                                     
    args_flat, _, params, in_tree, out_tree, _ = infer_params_fn(                                                                                                                 
  File "~/mambaforge/envs/lcms_polymer_env/lib/python3.10/site-packages/jax/_src/api.py", line 311, in infer_params                                             
    return pjit.common_infer_params(pjit_info_args, *args, **kwargs)                                                                                                              
  File "~/mambaforge/envs/lcms_polymer_env/lib/python3.10/site-packages/jax/_src/pjit.py", line 477, in common_infer_params                                     
    canonicalized_in_shardings_flat = _process_in_axis_resources(                                                                                                                 
  File "~/mambaforge/envs/lcms_polymer_env/lib/python3.10/site-packages/jax/_src/array.py", line 285, in __bool__                                               
    return bool(self._value)
jax._src.traceback_util.UnfilteredStackTrace: ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "~/workspace/lcms_polymer_model/./src/scripts/run_all.py", line 100, in run_all
    run_sample(
  File "~/workspace/lcms_polymer_model/./src/scripts/run_all.py", line 180, in run_sample
    loss, params_state, _ = step_func(
  File "~/mambaforge/envs/lcms_polymer_env/lib/python3.10/site-packages/jax/_src/array.py", line 285, in __bool__
    return bool(self._value)
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

Unfortunately I don't have any code I can share to reproduce.

### What jax/jaxlib version are you using?

jax 0.4.8, jaxlib 0.4.7 (installed via conda-forge)

### Which accelerator(s) are you using?

GPU

### Additional system info

Ubuntu 22.04.2 LTS

### NVIDIA GPU info

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.105.01   Driver Version: 515.105.01   CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA TITAN RTX    Off  | 00000000:21:00.0 Off |                  N/A |
| 36%   43C    P0    33W / 280W |      0MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by jongyaoY** [comment]
I am using jax 0.4.13, and I came across the same issue, but it occurs only by chance. Lucky enough it gave me the trace of the error this time:

```bash
File ".../lib/python3.8/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File ".../lib/python3.8/site-packages/jax/_src/pjit.py", line 250, in cache_miss
    outs, out_flat, out_tree, args_flat, jaxpr = _python_pjit_helper(
  File ".../lib/python3.8/site-packages/jax/_src/pjit.py", line 158, in _python_pjit_helper
    args_flat, _, params, in_tree, out_tree, _ = infer_params_fn(
  File ".../lib/python3.8/site-packages/jax/_src/api.py", line 306, in infer_params
    return pjit.common_infer_params(pjit_info_args, *args, **kwargs)
  File ".../lib/python3.8/site-packages/jax/_src/pjit.py", line 501, in common_infer_params
    canonicalized_in_shardings_flat = _process_in_axis_resources(
jax._src.traceback_util.UnfilteredStackTrace: ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

Seems like it's something internal

**Comment by jakevdp** [comment]
@jongyaoY  – please open a new issue and provide code that reproduces the issue. Despite the similar error message, I suspect these two situations are unrelated.

As for the original issue: I'm not sure how we missed it, but I'm going to close it because it's not actionable without code to reproduce the error.

**Comment by jongyaoY** [comment]
> [@jongyaoY](https://github.com/jongyaoY) – please open a new issue and provide code that reproduces the issue. Despite the similar error message, I suspect these two situations are unrelated.
> 
> As for the original issue: I'm not sure how we missed it (sorry about that), but I'm going to close it because it's not actionable without code to reproduce the error.

Seems like my issue is related to [#24204](https://github.com/jax-ml/jax/issues/24204#issue-2575477292). As a new user, I spent quite long time to figure out what's possibly wrong; hoping jax can give more detail traceback for debugging
