### ISSUE TITLE
jax Exception with custom_partitioning in scan in sharded jit

### ISSUE THREAD

**Issue by Findus23** [jax-ml/jax#17382]
### Description

This bug is also reproducible on CPU, so I will describe the CPU-version here.

I am still on my way implementing sharded fftn into an application (https://github.com/google/jax/issues/16909).

In this case I wanted to apply an irfftn to some axis of a larger array and stumbled across this issue which is even reproducible without the actual fft code. 
I am using jax 0.4.8 (because any newer version gives incorrect results due to #16909), but will show below that the same also breaks on the latest jax version.

minimal example code:
```python
import os

import jax
from jax.experimental import mesh_utils
from jax.experimental.custom_partitioning import custom_partitioning
from jax.sharding import Mesh, NamedSharding, PartitionSpec as P

os.environ['XLA_FLAGS'] = f'--xla_force_host_platform_device_count=2'

devices = mesh_utils.create_device_mesh((2,))
device_mesh = Mesh(devices, axis_names=('gpus',))

N = 8
sharding2d = NamedSharding(device_mesh, P(None, "gpus"))

with device_mesh:
    def main():
        psi = jax.numpy.zeros(shape=(1, 8, 8, 5, 3))

        original_shape = psi.shape

        psi = jax.numpy.moveaxis(psi, -1, 1).reshape(-1, N, N, N // 2 + 1)

        @custom_partitioning
        def some_irfftn_like_function(x):
            return jax.numpy.zeros(shape=(N, N, N))

        def scan_func(carry, x):
            return 0, some_irfftn_like_function(x)

        _, psi = jax.lax.scan(scan_func, 0, psi)

        psi = jax.numpy.moveaxis(psi.reshape(original_shape[0], 3, N, N, N), 1, -1)

        return psi


    main = jax.jit(main, out_shardings=sharding2d)
    data = main()
```

This gives the following Jax exception when running:
> `AttributeError: 'NoneType' object has no attribute 'to_proto'`

<details><summary>Full Traceback</summary>
<p>

```
Traceback (most recent call last):
  File "mycode_dir/test_to_proto.py", line 35, in <module>
    data = main()
           ^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/pjit.py", line 238, in cache_miss
    outs, out_flat, out_tree, args_flat = _python_pjit_helper(
                                          ^^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/pjit.py", line 185, in _python_pjit_helper
    out_flat = pjit_p.bind(*args_flat, **params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/core.py", line 2592, in bind
    return self.bind_with_trace(top_trace, args, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/core.py", line 363, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/core.py", line 817, in process_primitive
    return primitive.impl(*tracers, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/pjit.py", line 1232, in _pjit_call_impl
    always_lower=False, lowering_platform=None).compile(
                                                ^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 2816, in compile
    self._executable = UnloadedMeshExecutable.from_hlo(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 3028, in from_hlo
    xla_executable = dispatch.compile_or_get_cached(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/dispatch.py", line 526, in compile_or_get_cached
    return backend_compile(backend, serialized_computation, compile_options,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/dispatch.py", line 471, in backend_compile
    return backend.compile(built_c, compile_options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/experimental/custom_partitioning.py", line 117, in _custom_partitioning_infer_sharding_from_operands
    [info.to_mesh_pspec_sharding(s.to_proto()) for s in arg_shardings],
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/experimental/custom_partitioning.py", line 117, in <listcomp>
    [info.to_mesh_pspec_sharding(s.to_proto()) for s in arg_shardings],
                                 ^^^^^^^^^^
jax._src.traceback_util.UnfilteredStackTrace: AttributeError: 'NoneType' object has no attribute 'to_proto'

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mycode_dir/test_to_proto.py", line 35, in <module>
    data = main()
           ^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/experimental/custom_partitioning.py", line 117, in _custom_partitioning_infer_sharding_from_operands
    [info.to_mesh_pspec_sharding(s.to_proto()) for s in arg_shardings],
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/experimental/custom_partitioning.py", line 117, in <listcomp>
    [info.to_mesh_pspec_sharding(s.to_proto()) for s in arg_shardings],
                                 ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'to_proto'
```

</p>
</details> 

Removing `out_shardings=sharding2d` makes the code work again (but of course uses too much RAM for very large `psi`) and removing `@custom_partitioning` also makes the example work (but without it one can't implement the sharded FFT). Interestingly it already breaks with just the `custom_partitioning` decorator without actually implementing the custom partitioning. Also changing `PartitionSpec(None, "gpus")` to  `PartitionSpec("gpus")` doesn't fix it, so the None does not seem to come from there.

When updating to the latest jax version (0.4.14), the same code still breaks, but this time with a completely different exception and stack trace (but I assume the fundamental reason is still the same).

> `AttributeError` 
(when accessing `self.decode_shardings` [here](https://github.com/google/jax/blob/jaxlib-v0.4.14/jax/experimental/custom_partitioning.py#L416))

<details><summary>Full Traceback</summary>
<p>

```
Traceback (most recent call last):
  File "mycode_dir/mount/test_to_proto.py", line 35, in <module>
    data = main()
           ^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/pjit.py", line 253, in cache_miss
    outs, out_flat, out_tree, args_flat, jaxpr = _python_pjit_helper(
                                                 ^^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/pjit.py", line 161, in _python_pjit_helper
    args_flat, _, params, in_tree, out_tree, _ = infer_params_fn(
                                                 ^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/api.py", line 324, in infer_params
    return pjit.common_infer_params(pjit_info_args, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/pjit.py", line 491, in common_infer_params
    jaxpr, consts, canonicalized_out_shardings_flat = _pjit_jaxpr(
                                                      ^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/pjit.py", line 969, in _pjit_jaxpr
    jaxpr, final_consts, out_type = _create_pjit_jaxpr(
                                    ^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/linear_util.py", line 345, in memoized_fun
    ans = call(fun, *args)
          ^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/pjit.py", line 922, in _create_pjit_jaxpr
    jaxpr, global_out_avals, consts = pe.trace_to_jaxpr_dynamic(
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/interpreters/partial_eval.py", line 2155, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/interpreters/partial_eval.py", line 2177, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/linear_util.py", line 188, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "mycode_dir/mount/test_to_proto.py", line 29, in main
    _, psi = jax.lax.scan(scan_func, 0, psi)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/lax/control_flow/loops.py", line 254, in scan
    init_flat, carry_avals, carry_avals_out, init_tree, *rest = _create_jaxpr(init)
                                                                ^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/lax/control_flow/loops.py", line 240, in _create_jaxpr
    jaxpr, consts, out_tree = _initial_style_jaxpr(
                              ^^^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/lax/control_flow/common.py", line 65, in _initial_style_jaxpr
    jaxpr, consts, out_tree = _initial_style_open_jaxpr(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/lax/control_flow/common.py", line 59, in _initial_style_open_jaxpr
    jaxpr, _, consts = pe.trace_to_jaxpr_dynamic(wrapped_fun, in_avals, debug)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/interpreters/partial_eval.py", line 2155, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/interpreters/partial_eval.py", line 2177, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/linear_util.py", line 188, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "mycode_dir/mount/test_to_proto.py", line 27, in scan_func
    return 0, some_irfftn_like_function(x)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/experimental/custom_partitioning.py", line 451, in __call__
    decode_shardings=self.decode_shardings,
                     ^^^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/custom_api_util.py", line 26, in forward_attr
    raise AttributeError
jax._src.traceback_util.UnfilteredStackTrace: AttributeError

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mycode_dir/mount/test_to_proto.py", line 35, in <module>
    data = main()
           ^^^^^^
  File "mycode_dir/mount/test_to_proto.py", line 29, in main
    _, psi = jax.lax.scan(scan_func, 0, psi)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "mycode_dir/mount/test_to_proto.py", line 27, in scan_func
    return 0, some_irfftn_like_function(x)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/experimental/custom_partitioning.py", line 451, in __call__
    decode_shardings=self.decode_shardings,
                     ^^^^^^^^^^^^^^^^^^^^^
  File "virtualenv_dir/jaxtests/lib/python3.11/site-packages/jax/_src/custom_api_util.py", line 26, in forward_attr
    raise AttributeError
AttributeError
```

</p>
</details> 

It would be really great if someone could look into this as I am not really sure how to avoid this issue.

### What jax/jaxlib version are you using?

0.4.8 and 0.4.14

### Which accelerator(s) are you using?

CPU and GPU (same issue on both)

### Additional system info

Python 3.11.5, Linux

**Comment by Findus23** [comment]
It seems like the `AttributeError` in the latest version is because of the missing `some_irfftn_like_function.def_partition()`.

But if I add something like 
```python
def test():
    return jax.numpy.zeros(shape=(N, N, N))


def supported_sharding(sharding, shape):
    rank = len(shape.shape)
    max_shared_dims = min(len(sharding.spec), rank - 1)
    names = tuple(sharding.spec[:max_shared_dims]) + tuple(None for _ in range(rank - max_shared_dims))
    return NamedSharding(sharding.mesh, P(*names))


def partition(arg_shapes, result_shape):
    result_shardings = jax.tree_map(lambda x: x.sharding, result_shape)
    arg_shardings = jax.tree_map(lambda x: x.sharding, arg_shapes)
    return test, supported_sharding(arg_shardings[0], arg_shapes[0]), (
        supported_sharding(arg_shardings[0], arg_shapes[0]),)


def infer_sharding_from_operands_here(arg_shapes, result_shape):
    print(arg_shapes)
    arg_shardings = jax.tree_map(lambda x: x.sharding, arg_shapes)
    print(arg_shardings)
    return supported_sharding(arg_shardings[0], arg_shapes[0])
```

I get a `AttributeError: 'NoneType' object has no attribute 'spec'` in `max_shared_dims = min(len(sharding.spec), rank - 1)` because `arg_shapes` is `(ShapeDtypeStruct(shape=(8, 8, 5), dtype=float32),)` and `arg_shardings` is `(None,)`.
