### ISSUE TITLE
[jax2tf] jax.random.split fails on CUDA

### ISSUE THREAD

**Issue by kylestach** [jax-ml/jax#17816]
### Description

I'm unable to use `jax.random.split` in code that gets converted with `tf2jax`. Example:
```python
def f(k: jax.Array):
    return jax.random.split(k, 2)[0]
ftf = jax2tf.convert(f, polymorphic_shapes=["(2)"])
print("JAX", f(jax.random.PRNGKey(42)))
print("TF", ftf(tf.convert_to_tensor(jax.random.PRNGKey(42))))
```
Expected result:
```
JAX [2465931498 3679230171]
TF [2465931498 3679230171]
```
Actual result:
```
JAX [2465931498 3679230171]
2023-09-27 15:05:00.097533: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at xla_compile_on_demand_op.cc:292 : UNIMPLEMENTED: No registered implementation for custom call to "cu_threefry2x32" for platform "CUDA"
Traceback (most recent call last):
  File "main.py", line 109, in <module>
    main()
  File "main.py", line 65, in main
    print("TF", ftf(tf.convert_to_tensor(jax.random.PRNGKey(42))))
  File "<PYTHONSITEPACKAGES>/jax/experimental/jax2tf/jax2tf.py", line 417, in converted_fun_tf
    outs_flat_tf = converted_fun_flat_with_custom_gradient_tf(*args_flat_tf)
  File "<PYTHONSITEPACKAGES>/tensorflow/python/ops/custom_gradient.py", line 343, in __call__
    return self._d(self._f, a, k)
  File "<PYTHONSITEPACKAGES>/tensorflow/python/ops/custom_gradient.py", line 297, in decorated
    return _eager_mode_decorator(wrapped, args, kwargs)
  File "<PYTHONSITEPACKAGES>/tensorflow/python/ops/custom_gradient.py", line 543, in _eager_mode_decorator
    result, grad_fn = f(*args, **kwargs)
  File "<PYTHONSITEPACKAGES>/jax/experimental/jax2tf/jax2tf.py", line 409, in converted_fun_flat_with_custom_gradient_tf
    outs_tf, outs_avals, outs_tree = impl.run_fun_tf(args_flat_tf)
  File "<PYTHONSITEPACKAGES>/jax/experimental/jax2tf/jax2tf.py", line 518, in run_fun_tf
    results = _run_exported_as_tf(args_flat_tf, self.exported)
  File "<PYTHONSITEPACKAGES>/jax/experimental/jax2tf/jax2tf.py", line 877, in _run_exported_as_tf
    res = tfxla.call_module(args_flat_tf, **call_module_attrs)
  File "<PYTHONSITEPACKAGES>/tensorflow/compiler/tf2xla/python/xla.py", line 645, in call_module
    res = gen_xla_ops.xla_call_module(
  File "<PYTHONSITEPACKAGES>/tensorflow/compiler/tf2xla/ops/gen_xla_ops.py", line 337, in xla_call_module
    _ops.raise_from_not_ok_status(e, name)
  File "<PYTHONSITEPACKAGES>/tensorflow/python/framework/ops.py", line 5887, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access

```
Seems like tf2jax is spitting out `cu_threefry2x32` calls that don't correspond to valid TF ops.

### What jax/jaxlib version are you using?

jax 0.4.16, jaxlib 0.4.16+cuda12.cudnn89, tf-nightly 2.15.0.dev20230927

### Which accelerator(s) are you using?

GPU

### Additional system info

Ubuntu 22.04

### NVIDIA GPU info

```
Wed Sep 27 15:08:54 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.98                 Driver Version: 535.98       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA TITAN Xp                Off | 00000000:01:00.0 Off |                  N/A |
| 44%   68C    P0              76W / 250W |   1496MiB / 12288MiB |     24%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA TITAN Xp                Off | 00000000:02:00.0  On |                  N/A |
| 41%   66C    P0              66W / 250W |    144MiB / 12288MiB |     31%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA TITAN Xp                Off | 00000000:03:00.0 Off |                  N/A |
| 34%   57C    P2              68W / 250W |    558MiB / 12288MiB |     15%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```

**Comment by nireekshak** [comment]
Hi @kylestach, I tried to reproduce this issue with the latest JAX version 0.5.0 on colab notebook.It works without any error now. Please find the [gist](https://colab.sandbox.google.com/gist/nireekshak/8431d9597746f2f967be0db1cbb27d45/-17816ipynb.ipynb) for reference.
Thank you.
