### ISSUE TITLE
Distribution of gradient calculation to multiple GPUs

### ISSUE THREAD

**Issue by dream0777** [jax-ml/jax#1899]
Hello, dear JAX team.
I have a function to calculate gradient. And the speed of the computation is very important. Your JAX package provides a very, very good functionality with this. I appreciate you and your JAX.
But recently I have a small problem.
```python
m = (0,1,2,3,4,5,6)
grad_test_pw = jit(grad(test_pw,argnums=m))
grad_test_pw(phim,phiw,f0m,f0w,const,rho,theta,phif0,phi,f0)
```
the ```test_pw```is the function I work on with.
I tried the following method to calculate the gradient on two GPUs.
```python
def first(var):
    return test_pw(var[0],var[1],var[2],var[3],const,rho,theta,phif0,phi,f0)

def second(var):
    return test_pw(phim,phiw,f0m,f0w,np.asarray([var[0], var[1]]),var[2],var[3],phif0,phi,f0)

var1 = np.stack([phim,phiw,f0m,f0w], axis=0)
var1 = np.expand_dims(var1, axis=0)
var2 = np.stack([const[0],const[1],rho,theta], axis=0)
var2 = np.expand_dims(var2, axis=0)

first_grad = jit(jax.pmap(grad(first), devices=jax.devices()[:1]))
second_grad = jit(jax.pmap(grad(second), devices=jax.devices()[1:]))
print(first_grad(var1))
print(second_grad(var2))
```

But the total calculation speed is the same with on one GPU. I think it used two GPUs one by one.
I want to use two GPUs synchronosly, what method can I use? Use thread or process? I am not good in Python thread and process yet.

**Comment by jekbradbury** [comment]
If you want to run the same function simultaneously on two GPUs (for instance, with different inputs), use a single `pmap` (it has the semantics of "map this function over this array, but run each instance on a different device"). If you want to run _different_ functions simultaneously on two GPUs, just launch two `jit`s one after another with different values for `device` (they will run asynchronously).

**Comment by Dream7-Kim** [comment]
Thank you, the above code I added has two different functions need to be running on two different GPU.
As you can see I used ```jit``` for both functions, and it is exactly like you said, two functions are running simultaneously. When I record the calculation time for each function individually, it will be quick about double times, but when I simultaneously record calculation time, it will be same as the time using one GPU, and I have no time saving. Why does this happen? I think if use two cards, the total calculation time would be short, I mean time saving by more GPUs, but no time saving now.

**Comment by skye** [comment]
In your example, you're passing `devices` to `jit`, not `device` (no 's'). Passing `devices` should be an error. You need to pass `device=jax.devices()[1]` to use the second GPU.

**Comment by caihao** [comment]
```python
from jax import device_put, devices, jit
import jax.numpy as np
import numpy as onp


def f(x):
    return np.sum(x)


f0 = jit(f, device=devices()[0])
f1 = jit(f, device=devices()[1])

data = onp.random.rand(10000)

x0 = device_put(data, device=devices()[0])
x1 = device_put(data, device=devices()[1])

print("f on gpu 0:", f0(x0))
print("f on gpu 1:", f1(x1))
```

As I run this code on my machine, there are errors like this
```
f on gpu 0: 4949.328
2020-04-15 13:00:27.288577: E external/org_tensorflow/tensorflow/compiler/xla/python/local_client.cc:758] Execution of replica 0 failed: Invalid argument: executable is built for device CUDA:0 of type "GeForce RTX 2080 Ti"; cannot run it on device CUDA:1 of type "Tesla P100-PCIE-16GB"
Traceback (most recent call last):
  File "test3.py", line 21, in <module>
    print("f on gpu 1:", f1(x1))
  File "/usr/local/lib/python3.6/dist-packages/jax/api.py", line 150, in f_jitted
    out = xla.xla_call(flat_fun, *args_flat, device=device, backend=backend)
  File "/usr/local/lib/python3.6/dist-packages/jax/core.py", line 592, in call_bind
    outs = primitive.impl(f, *args, **params)
  File "/usr/local/lib/python3.6/dist-packages/jax/interpreters/xla.py", line 402, in _xla_call_impl
    return compiled_fun(*args)
  File "/usr/local/lib/python3.6/dist-packages/jax/interpreters/xla.py", line 486, in _execute_compiled
    out_bufs = compiled.Execute(input_bufs).destructure()
RuntimeError: Invalid argument: executable is built for device CUDA:0 of type "GeForce RTX 2080 Ti"; cannot run it on device CUDA:1 of type "Tesla P100-PCIE-16GB"
```
@jekbradbury 

Could you give me some advice?

**Comment by mattjj** [comment]
This is an old issue, but we're going to sort it out!

Actually, we're going to split this into two issues: the issue in the OP, and @caihao's question.

**Comment by hawkinsp** [comment]
Closing as stale, because `pmap` is no longer the recommended way to do parallelism, and parallelizing gradient computations is much easier with the modern `jit` parallelism.
