### ISSUE TITLE
Unable to load any libcudnn_engines_precompiled.so using jax.nn.dot_product_attention

### ISSUE THREAD

**Issue by zdcao121** [jax-ml/jax#23833]
### Description

I am calling `jax.nn.dot_product_attention` with the following line:

```
dpsa_cudnn = jax.nn.dot_product_attention(query, key, value, implementation='cudnn')
```
However, this throws the following error:
```
2024-09-23 10:43:47.563053: W external/xla/xla/service/gpu/nvptx_compiler.cc:893] The NVIDIA driver's CUDA version is 12.4 which is older than the PTX compiler version 12.6.68. Because the driver is older than the PTX compiler version, XLA is disabling parallel compilation, which may slow down compilation. You should update your NVIDIA driver or use the NVIDIA-provided CUDA forward compatibility packages.
Unable to load any of {libcudnn_engines_precompiled.so.9.4.0, libcudnn_engines_precompiled.so.9.4, libcudnn_engines_precompiled.so.9, libcudnn_engines_precompiled.so}
Traceback (most recent call last):
  File "/home/zdcao/website/distance/crystal_gpt/./test_flash_attn.py", line 19, in <module>
    dpsa_cudnn = jax.nn.dot_product_attention(query, key, value, implementation='cudnn')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/zdcao/envs/rl/lib/python3.11/site-packages/jax/_src/nn/functions.py", line 1025, in dot_product_attention
    out = cudnn_dot_product_attention(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/zdcao/envs/rl/lib/python3.11/site-packages/jax/_src/cudnn/fused_attention_stablehlo.py", line 1061, in dot_product_attention
    output = _dot_product_attention(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/zdcao/envs/rl/lib/python3.11/site-packages/jax/_src/cudnn/fused_attention_stablehlo.py", line 953, in _dot_product_attention
    output = _dot_product_attention_fwd(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/zdcao/envs/rl/lib/python3.11/site-packages/jax/_src/cudnn/fused_attention_stablehlo.py", line 330, in _dot_product_attention_fwd
    outputs = _dot_product_attention_fwd_p_wrapper.bind(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/zdcao/envs/rl/lib/python3.11/site-packages/jax/_src/cudnn/fused_attention_stablehlo.py", line 374, in _dot_product_attention_fwd_impl
    outputs = _dot_product_attention_fwd_p.bind(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: The stride for the last dimension corresponding to the embedding size per head should be 1 for input_names::K
in external/xla/xla/stream_executor/cuda/cuda_dnn.cc(8233): 'graph_.build_operation_graph(cudnn->handle())' 
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.33
jaxlib: 0.4.33
numpy:  2.1.1
python: 3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0]
jax.devices (1 total, 1 local): [CudaDevice(id=0)]
process_count: 1
platform: uname_result(system='Linux', node='node002', release='3.10.0-1062.12.1.el7.x86_64', version='#1 SMP Tue Feb 4 23:02:59 UTC 2020', machine='x86_64')


$ nvidia-smi
Mon Sep 23 10:49:00 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.90.07              Driver Version: 550.90.07      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100 80GB PCIe          Off |   00000000:16:00.0 Off |                  Off |
| N/A   38C    P0             62W /  300W |     425MiB /  81920MiB |      2%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A     98693      C   python                                        416MiB |
+-----------------------------------------------------------------------------------------+
```

**Comment by Cjkkkk** [comment]
Seems that the head dim of K doesn't have stride 1 which is required by cuDNN, could you provide a repo with how QKV is constructed?

**Comment by zdcao121** [comment]
QKV is constructed as follows:

```
# Define the input shapes
batch_size = 1000
nhead = 4
seq_len = 105
hidden_dim = 64

key = jax.random.PRNGKey(42)
# Generate random input data
key, key1, key2, key3 = jax.random.split(key, 4)
query = jax.random.normal(key1, (batch_size, seq_len, nhead, hidden_dim), dtype=jnp.float16)
key = jax.random.normal(key2, (batch_size, seq_len, nhead, hidden_dim), dtype=jnp.float16)
value = jax.random.normal(key3, (batch_size, seq_len, nhead, hidden_dim),  dtype=jnp.float16)
```

**Comment by Cjkkkk** [comment]
Thanks! let me try reproducing this.

**Comment by zdcao121** [comment]
@Cjkkkk have there been any updates?

**Comment by Cjkkkk** [comment]
Sorry, it fell through the cracks. I'm not able to reproduce with this example:
```
from functools import partial
import jax
import jax.numpy as jnp
from jax.nn import (
    dot_product_attention,
)

# Define the input shapes
batch_size = 1000
nhead = 4
seq_len = 105
hidden_dim = 64

key = jax.random.PRNGKey(42)
# Generate random input data
key, key1, key2, key3 = jax.random.split(key, 4)
query = jax.random.normal(key1, (batch_size, seq_len, nhead, hidden_dim), dtype=jnp.float16)
key = jax.random.normal(key2, (batch_size, seq_len, nhead, hidden_dim), dtype=jnp.float16)
value = jax.random.normal(key3, (batch_size, seq_len, nhead, hidden_dim),  dtype=jnp.float16)

dpsa_cudnn = jax.jit(
  partial(dot_product_attention, implementation='cudnn')
)

out = dpsa_cudnn(query, key, value)
print(out[0,0,0,0])
```

I'm using cuDNN 9.4 + CUDA 12.6 on Hopper with XLA and JAX at head.

**Comment by zdcao121** [comment]
I  use the cudnn 9.5 + CUDA12.6. It may be due to version incompatibility.

**Comment by Cjkkkk** [comment]
I also tried cudnn 9.5 + CUDA 12.6. I tried both on A100 and H100. Still can't reproduce this. Is there anything specific about your testing environment? Maybe using some specific commits from old JAX/XLA?

**Comment by zdcao121** [comment]
It seems that this issue is caused by our outdated `CentOS` version and the absence of pre-compiled libraries. This error no longer happens when using the `ubuntu+cuda12.5` image.
