### ISSUE TITLE
checkify doesn't work with shard_map output array

### ISSUE THREAD

**Issue by Findus23** [jax-ml/jax#23946]
### Description

To clarify: I don't mean using `checkify.check` inside a `shard_map` function, but using the output of a `shard_map` function and `checkify.check` in the same function and then applying `checkify.checkify` to it.

Example:

```python
import os

from jax import Array
from jax.experimental.shard_map import shard_map
from jax.sharding import Mesh, PartitionSpec
from jax.experimental import mesh_utils, checkify

os.environ['XLA_FLAGS'] = f'--xla_force_host_platform_device_count=4'

import jax
import jax.numpy as jnp

devices = mesh_utils.create_device_mesh((4,))

mesh = Mesh(devices, axis_names=('a',))
sharding = jax.sharding.NamedSharding(mesh, PartitionSpec('a'))

def some_function():
    a = jnp.zeros(1000)
    return a

some_function_shard_map = shard_map(
    some_function,
    mesh=mesh,
    in_specs=PartitionSpec(None),
    out_specs=PartitionSpec("a")
)

def main_function():
    something = some_function_shard_map()
    checkify.check(jnp.all(something == 0), "failed")
    return something

main_function = checkify.checkify(main_function)

main_function = jax.jit(main_function)  # same result without this line

error: checkify.Error
error, out = main_function()
error.throw()
```

output:
```text
Traceback (most recent call last):
  File ".../checkify_test_2.py", line 43, in <module>
    error, out = main_function()
  File ".../checkify_test_2.py", line 33, in main_function
    something = some_function_shard_map()
jax._src.source_info_util.JaxStackTraceBeforeTransformation: TypeError: ShardMapPrimitive.bind() got an unexpected keyword argument 'out_names'

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".../checkify_test_2.py", line 43, in <module>
    error, out = main_function()
                 ^^^^^^^^^^^^^^^
TypeError: ShardMapPrimitive.bind() got an unexpected keyword argument 'out_names'
```

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.33
jaxlib: 0.4.33
numpy:  2.0.1
python: 3.12.6 (main, Sep  7 2024, 14:20:15) [GCC 14.2.0]
jax.devices (4 total, 4 local): [CpuDevice(id=0) CpuDevice(id=1) CpuDevice(id=2) CpuDevice(id=3)]
process_count: 1
platform: uname_result(system='Linux', node='standpc', release='6.10.9-amd64', version='#1 SMP PREEMPT_DYNAMIC Debian 6.10.9-1 (2024-09-08)', machine='x86_64')
```

**Comment by yashk2810** [comment]
If you use JAX from HEAD, then it should work!

**Comment by Findus23** [comment]
Indeed, using jax(lib)-0.4.34.dev20240926 this seems to work as expected
