### ISSUE TITLE
`CUDA_ERROR_ILLEGAL_ADDRESS`

### ISSUE THREAD

**Issue by PhilipVinc** [jax-ml/jax#25002]
### Description

Hello,

we've got a code (that we can share) that crashes with the error `CUDA_ERROR_ILLEGAL_ADDRESS` on jax:CUDA, which seems like we've hit some XLA compilation bug?
The code is complex (And full of `.at[].set()`), and attempts to produce a MWE fail because small changes to the python code make the error disappear.

We can share the script (and a requirements.txt file) to reproduce it, but maybe you just need the HLO code to reproduce it?
Let us know if we can provide something that can be useful to debug it.

cc @AmedSho97

```python
E1120 10:59:55.894873   35984 pjrt_stream_executor_client.cc:3067] Execution of replica 0 failed: INTERNAL: Failed to retrieve branch_index value on stream 0x5583cca477e0: CUDA error: Could not synchronize CUDA stream: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered.
Traceback (most recent call last):
  File "/mnt/beegfs/workdir/ahmedeo.shokry/Hubbard_4x4_BF_conv_U_3_6_trans_inv/test_trans_HFSD.py", line 146, in <module>
    print(vstate.expect(H))
          ^^^^^^^^^^^^^^^^
  File "/mnt/beegfs/workdir/ahmedeo.shokry/mambaforge/envs/netket_sharding_local/lib/python3.11/site-packages/netket/utils/timing.py", line 230, in timed_function
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/beegfs/workdir/ahmedeo.shokry/mambaforge/envs/netket_sharding_local/lib/python3.11/site-packages/netket/vqs/mc/mc_state/state.py", line 631, in expect
    return expect(self, O, self.chunk_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/beegfs/workdir/ahmedeo.shokry/mambaforge/envs/netket_sharding_local/lib/python3.11/site-packages/plum/function.py", line 383, in __call__
    return _convert(method(*args, **kw_args), return_type)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/beegfs/workdir/ahmedeo.shokry/mambaforge/envs/netket_sharding_local/lib/python3.11/site-packages/netket/vqs/mc/mc_state/expect.py", line 111, in expect
    return _expect(
           ^^^^^^^^
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Failed to retrieve branch_index value on stream 0x5583cca477e0: CUDA error: Could not synchronize CUDA stream: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered.
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
2024-11-20 10:59:55.937334: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:1144] failed to unload module 0x5583eb358f00; leaking: INTERNAL: CUDA error: : CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
```

### System info (python version, jaxlib version, accelerator, etc.)

```python
jax: 0.4.33
jaxlib: 0.4.33
numpy: 2.0.2
python: 3.11.10 | packaged by conda-forge | (main, Sep 22 2024, 14:10:38) [GCC 13.3.0]
jax.devices (1 total, 1 local): [CpuDevice(id=0)]
process_count: 1
platform: uname_result(system='Linux', node='cholesky-login01', release='3.10.0-1062.el7.x86_64', version='#1 SMP Wed Aug 7 18:08:02 UTC 2019', machine='x86_64')
```

**Comment by hawkinsp** [comment]
Well, we'd need to reproduce it somehow. It's possible the HLO will suffice to reproduce it, so we could certainly try that? Can you share an HLO dump? (Set `XLA_FLAGS=--xla_dump_to=/somewhere` and zip up `/somewhere` and attach it to the issue.)

**Comment by vdbwouter** [comment]
I've been running into a similar (or the same?) issue, where my Python script would crash with an `CUDA_ERROR_ILLEGAL_ADDRESS`. I've managed to simplify my code by quite a lot, and have gotten to the following MWE:

```python
# mwe.py
from jax import jit
import jax.numpy as jnp

@jit
def test(b: jnp.ndarray, d: jnp.ndarray):
    i = jnp.searchsorted(d, b[:,-1])
    return jnp.zeros_like(d, dtype=jnp.uint8).at[i].set(1, mode="drop")

SIZE_B = 2500
SIZE_C = 11000**2

a = jnp.zeros((1,1,1), dtype=jnp.uint8)
b = jnp.arange(SIZE_B**2).reshape((SIZE_B,SIZE_B))
c = jnp.zeros(SIZE_C, dtype=jnp.bool)
d = jnp.arange(1)

e = test(b, d)
```

Removing the JIT annotation or changing the order of allocations in any way seems to cause the error to disappear, as does making either SIZE_B or SIZE_C much smaller. Furthermore, it also requires the environment variable `XLA_PYTHON_CLIENT_ALLOCATOR` to be set to `platform`.

Running this script gives me the following output:

```
$ XLA_PYTHON_CLIENT_ALLOCATOR=platform python ./mwe.py
E0224 15:06:03.877603   42666 cuda_executor.cc:498] failed to free device memory at 0x754311602800; result: INTERNAL: CUDA error: : CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
E0224 15:06:03.877631   42666 pjrt_stream_executor_client.cc:3045] Execution of replica 0 failed: INTERNAL: Failed to complete all kernels launched on stream 0x33b2c110: CUDA error: Could not synchronize CUDA stream: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
Traceback (most recent call last):
  File "~/jax_repro/./mwe.py", line 17, in <module>
    e = test(b, d)
        ^^^^^^^^^^
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Failed to complete all kernels launched on stream 0x33b2c110: CUDA error: Could not synchronize CUDA stream: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
E0224 15:06:03.881059   42666 cuda_executor.cc:248] failed to unload module 0x33e62ca0; leaking: INTERNAL: CUDA error: : CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
... (similar errors trimmed)
```

I've tested this on three different GPUs, an A4000-Ada, A5000-Ada and an RTX 3080 Mobile. This was tested on JAX version 0.5.0, with Python version 3.12.3 and 3.12.8 on Linux. If you want any more details, feel free to let me know.

**Comment by vdbwouter** [comment]
I've spent a bit of time digging into the generated LLVM IR (found using `--xla_dump_to=./xla_dump`). The LLVM IR for the `test` function is as follows:

```llvm
; ModuleID = 'jit_test'
source_filename = "jit_test"
target datalayout = "e-i64:64-i128:128-v16:16-v32:32-n16:32:64"
target triple = "nvptx64-nvidia-cuda"

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(argmem: readwrite)
define void @input_scatter_fusion(ptr noalias nocapture writeonly align 128 dereferenceable(8) %0, ptr noalias nocapture readonly align 16 dereferenceable(25000000) %1) local_unnamed_addr #0 {
  %3 = addrspacecast ptr %1 to ptr addrspace(1)
  %4 = addrspacecast ptr %0 to ptr addrspace(1)
  %5 = tail call i32 @llvm.nvvm.read.ptx.sreg.tid.x(), !range !4
  %6 = tail call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x(), !range !5
  %7 = mul nuw nsw i32 %5, 2500
  %8 = mul nuw nsw i32 %6, 320000
  %9 = add nuw nsw i32 %7, %8
  %10 = zext nneg i32 %9 to i64
  %11 = getelementptr inbounds i32, ptr addrspace(1) %3, i64 %10
  %12 = load i32, ptr addrspace(1) %11, align 16, !invariant.load !6
  %13 = lshr i32 %12, 30
  %14 = and i32 %13, 2
  %15 = add i32 %14, %12
  %16 = icmp ult i32 %15, 2
  %17 = shl nuw nsw i32 %6, 7
  %18 = or disjoint i32 %17, %5
  %19 = icmp samesign ult i32 %18, 2500
  %or.cond = and i1 %19, %16
  %20 = zext nneg i32 %15 to i64
  %21 = getelementptr inbounds i32, ptr addrspace(1) %4, i64 %20
  br i1 %or.cond, label %22, label %23

22:                                               ; preds = %2
  store atomic i32 1, ptr addrspace(1) %21 unordered, align 4
  br label %23

23:                                               ; preds = %22, %2
  ret void
}
```

If you look at the load for `%12`, you can see that no bounds checking is being done for the index. `compute-sanitizer --tool memcheck` supports this, as this gives the following output:

```
========= Invalid __global__ read of size 4 bytes
=========     at input_scatter_fusion+0x80
=========     by thread (96,0,0) in block (19,0,0)
=========     Address 0x7326f181be00 is out of bounds
=========     and is 280,001 bytes after the nearest allocation at 0x7326f0000000 of size 25,000,000 bytes
```

Calculating the value for `%9`, we find an index of 6320000, 70000 past the last index of `b` (`%1`), which matches the out of bounds address exactly (280,001 bytes = 70000 elements). Therefore, it seems there is a bug somewhere in the codegen, which accidentally removes the boundscheck.

**Comment by akuegel** [comment]
Can you please also post the HLO before optimizations here that was dumped?

**Comment by vdbwouter** [comment]
Yes, of course! Here's the HLO before optimations (`module_0013.jit_test.before_optimizations.txt`):

```hlo
HloModule jit_test, entry_computation_layout={(s32[2500,2500]{1,0}, s32[1]{0})->s32[1]{0}}, allow_spmd_sharding_propagation_to_parameters={true,true}, allow_spmd_sharding_propagation_to_output={true}

region_0.13 {
  Arg_0.14 = s32[] parameter(0), metadata={op_name="jit(test)/jit(main)/scatter"}
  ROOT Arg_1.15 = s32[] parameter(1), metadata={op_name="jit(test)/jit(main)/scatter"}
}

ENTRY main.17 {
  Arg_1.2 = s32[1]{0} parameter(1), metadata={op_name="d"}
  Arg_0.1 = s32[2500,2500]{1,0} parameter(0), metadata={op_name="b"}
  slice.7 = s32[2500,1]{1,0} slice(Arg_0.1), slice={[0:2500], [0:1]}, metadata={op_name="jit(test)/jit(main)/slice" source_file="/home/wouter/jax_repro/./mwe.py" source_line=6}
  reshape.8 = s32[2500]{0} reshape(slice.7), metadata={op_name="jit(test)/jit(main)/squeeze" source_file="/home/wouter/jax_repro/./mwe.py" source_line=6}
  constant.5 = s32[] constant(0)
  broadcast.6 = s32[2500]{0} broadcast(constant.5), dimensions={}
  compare.9 = pred[2500]{0} compare(reshape.8, broadcast.6), direction=LT, metadata={op_name="jit(test)/jit(main)/lt" source_file="/home/wouter/jax_repro/./mwe.py" source_line=6}
  constant.3 = s32[] constant(1)
  broadcast.4 = s32[2500]{0} broadcast(constant.3), dimensions={}
  add.10 = s32[2500]{0} add(reshape.8, broadcast.4), metadata={op_name="jit(test)/jit(main)/add" source_file="/home/wouter/jax_repro/./mwe.py" source_line=6}
  select.11 = s32[2500]{0} select(compare.9, add.10, reshape.8), metadata={op_name="jit(test)/jit(main)/select_n" source_file="/home/wouter/jax_repro/./mwe.py" source_line=6}
  reshape.12 = s32[2500,1]{1,0} reshape(select.11), metadata={op_name="jit(test)/jit(main)/broadcast_in_dim" source_file="/home/wouter/jax_repro/./mwe.py" source_line=6}
  ROOT scatter.16 = s32[1]{0} scatter(Arg_1.2, reshape.12, broadcast.4), update_window_dims={}, inserted_window_dims={0}, scatter_dims_to_operand_dims={0}, index_vector_dim=1, to_apply=region_0.13, metadata={op_name="jit(test)/jit(main)/scatter" source_file="/home/wouter/jax_repro/./mwe.py" source_line=6}
} // main.17
```

I also provided the entire XLA dump, in case you're interested: [xla_dump.zip](https://github.com/user-attachments/files/18984583/xla_dump.zip). If you need anything else, feel free to let me know.

**Comment by akuegel** [comment]
Thank you very much :)
