### ISSUE TITLE
Cannot generate from `jax.experimental.sparse.random_bcoo` for arrays larger than the int32 max 

### ISSUE THREAD

**Issue by lengstrom** [jax-ml/jax#25182]
### Description

`jax.experimental.sparse.random_bcoo` yields an error for arrays with size larger than the int32 max. It looks like one cannot generate random indices that overflow int32 even if the specified index dtype if int64.

Here is code to reproduce:

```python
import jax
import jax.numpy as jnp
from jax.experimental.sparse import random_bcoo

key = jax.random.PRNGKey(0)
shape = (4096, 1769472)
dtype = jnp.float32
nse = 8.964381565185707e-05
indices_dtype = jnp.int64
random_bcoo(key, shape, dtype=dtype, indices_dtype=indices_dtype, nse=nse)
```

yields error

```
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/xfs/home/engstrom/conda_envs/ajax/lib/python3.10/site-packages/jax/experimental/sparse/random.py", line 87, in random_bcoo
    indices = _indices(index_keys).reshape(indices_shape)
  File "/mnt/xfs/home/engstrom/conda_envs/ajax/lib/python3.10/site-packages/jax/experimental/sparse/random.py", line 80, in _indices
    flat_ind = random.choice(key, sparse_size, shape=(nse,),
  File "/mnt/xfs/home/engstrom/conda_envs/ajax/lib/python3.10/site-packages/jax/_src/random.py", line 631, in choice
    arr = jnp.asarray(a)
  File "/mnt/xfs/home/engstrom/conda_envs/ajax/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 5592, in asarray
    return array(a, dtype=dtype, copy=bool(copy), order=order, device=device)
  File "/mnt/xfs/home/engstrom/conda_envs/ajax/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 5354, in array
    _ = dtypes.coerce_to_array(object, dtype)
OverflowError: Python int 7247757312 too large to convert to int32
```

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.35
jaxlib: 0.4.34
numpy:  1.26.4
python: 3.10.14 (main, Mar 21 2024, 16:24:04) [GCC 11.2.0]
device info: NVIDIA A100-PCIE-40GB-1, 1 local devices"
process_count: 1
platform: uname_result(system='Linux', node='', release='5.15.0-118-generic', version='#128-Ubuntu SMP Fri Jul 5 09:28:59 UTC 2024', machine='x86_64')

$ nvidia-smi
Thu Nov 28 15:02:31 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-PCIE-40GB          On  |   00000000:01:00.0 Off |                    0 |
| N/A   38C    P0             36W /  250W |   40310MiB /  40960MiB |      0%      Default |
|                                         |                        |             Disabled |
```

**Comment by lengstrom** [comment]
never mind i forgot to enable 64 bit dtypes
