### ISSUE TITLE
[//tests/mosaic:gpu_test_gpu] Wrong results on H100

### ISSUE THREAD

**Issue by gpupuck** [jax-ml/jax#25218]
### Description

Sometime on Nov. 22, `//tests/mosaic:gpu_test_gpu` was added with `jax_test_gpu` tag and our internal and external CI started to pick up this test target. However it failed with wrong results from the beginning on H100.

Essentially we are doing something like `bazel test --//jax:build_jaxlib=false --test_tag_filters=jax_test_gpu --@local_config_cuda//:enable_cuda --cache_test_results=auto //tests/mosaic:gpu_test_gpu`.

```
FAIL: test_scalar_argument0 (<class 'jax.numpy.uint64'>) (__main__.MemRefTest)
MemRefTest.test_scalar_argument0 (<class 'jax.numpy.uint64'>)
test_scalar_argument(<class 'jax.numpy.uint64'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/cfd1b2cc6fe180f3eb424db6004de364/execroot/__main__/bazel-out/k8-opt/bin/tests/mosaic/gpu_test_gpu.runfiles/pypi_absl_py/site-packages/absl/testing/parameterized.py", line 323, in bound_param_test
    return test_method(self, testcase_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/bazel/_bazel_root/cfd1b2cc6fe180f3eb424db6004de364/execroot/__main__/bazel-out/k8-opt/bin/tests/mosaic/gpu_test_gpu.runfiles/__main__/tests/mosaic/gpu_test.py", line 386, in test_scalar_argument
    np.testing.assert_array_equal(res, expected)
  File "/root/.cache/bazel/_bazel_root/cfd1b2cc6fe180f3eb424db6004de364/execroot/__main__/bazel-out/k8-opt/bin/tests/mosaic/gpu_test_gpu.runfiles/pypi_numpy/site-packages/numpy/_utils/__init__.py", line 85, in wrapper
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/bazel/_bazel_root/cfd1b2cc6fe180f3eb424db6004de364/execroot/__main__/bazel-out/k8-opt/bin/tests/mosaic/gpu_test_gpu.runfiles/pypi_numpy/site-packages/numpy/testing/_private/utils.py", line 1021, in assert_array_equal
    assert_array_compare(operator.__eq__, actual, desired, err_msg=err_msg,
  File "/root/.cache/bazel/_bazel_root/cfd1b2cc6fe180f3eb424db6004de364/external/python_x86_64-unknown-linux-gnu/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/bazel/_bazel_root/cfd1b2cc6fe180f3eb424db6004de364/execroot/__main__/bazel-out/k8-opt/bin/tests/mosaic/gpu_test_gpu.runfiles/pypi_numpy/site-packages/numpy/testing/_private/utils.py", line 885, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

Mismatched elements: 16384 / 16384 (100%)
Max absolute difference among violations: 4575657221408423936
Max relative difference among violations: 1.0894422e+17
 ACTUAL: array([[4575657221408423978, 4575657221408423978, 4575657221408423978,
        ..., 4575657221408423978, 4575657221408423978,
        4575657221408423978],...
 DESIRED: array([[42, 42, 42, ..., 42, 42, 42],
       [42, 42, 42, ..., 42, 42, 42],
       [42, 42, 42, ..., 42, 42, 42],...

```

### System info (python version, jaxlib version, accelerator, etc.)

```
tf-docker /opt/jax > python3 -c "import jax; jax.print_environment_info()"
jax:    0.4.36.dev20241123+e53ff2cbf
jaxlib: 0.4.36.dev20241203
numpy:  1.26.4
python: 3.11.10 (main, Sep  7 2024, 18:35:41) [GCC 11.4.0]
device info: NVIDIA H100 80GB HBM3-8, 8 local devices"
process_count: 1
platform: uname_result(system='Linux', node='45b7b0384a16', release='5.15.0-1065-nvidia', version='#66-Ubuntu SMP Fri Aug 30 13:56:20 UTC 2024', machine='x86_64')


$ nvidia-smi
Tue Dec  3 00:36:37 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.06             Driver Version: 535.183.06   CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA H100 80GB HBM3          On  | 00000000:1B:00.0 Off |                    0 |
| N/A   39C    P0             131W / 500W |    549MiB / 81559MiB |      0%      Default |
|                                         |                      |             Disabled |
...
```

**Comment by hawkinsp** [comment]
Closing as likely stale.
