### ISSUE TITLE
[Pallas TPU] `pl.load` does not work inside TPU kernels

### ISSUE THREAD

**Issue by ayaka14732** [jax-ml/jax#25230]
### Description

```python
import functools
import jax
from jax.experimental import pallas as pl
import jax.numpy as jnp

m, n = 4, 2

@jax.named_scope('test_kernel')
@functools.partial(
    pl.pallas_call,
    out_shape=jax.ShapeDtypeStruct((m, n), jnp.int32),
    # interpret=True,
    debug=True,
)
def kernel(x_ref, o_ref):
    idx = (
        jnp.arange(m, dtype=jnp.int32)[:, None],
        jnp.arange(n, dtype=jnp.int32)[None],
    )
    x = pl.load(x_ref, idx)
    o_ref[...] = x

def main():
    x = jnp.arange(m * n, dtype=jnp.int32).reshape((m, n))
    out = kernel(x)
    print(out)

if __name__ == '__main__':
    main()
```

Error:

```
The kernel jaxpr for pallas_call kernel at /home/ayx/jax/3.py:8:
{ lambda ; a:MemRef<None>{int32[4,2]} b:MemRef<None>{int32[4,2]}. let
    c:i32[4] = iota[dimension=0 dtype=int32 shape=(4,) sharding=None] 
    d:i32[4,1] = broadcast_in_dim[
      broadcast_dimensions=(0,)
      shape=(4, 1)
      sharding=None
    ] c
    e:i32[2] = iota[dimension=0 dtype=int32 shape=(2,) sharding=None] 
    f:i32[1,2] = broadcast_in_dim[
      broadcast_dimensions=(1,)
      shape=(1, 2)
      sharding=None
    ] e
    g:i32[4,2] = broadcast_to[shape=(4, 2)] d
    h:i32[4,2] = broadcast_to[shape=(4, 2)] f
    i:i32[4,2] <- a[g,h]
    b[:,:] <- i
  in () }
Traceback (most recent call last):
  File "/home/ayx/jax/jax/_src/pallas/mosaic/lowering.py", line 841, in jaxpr_subcomp
    ans = lowering_rules[eqn.primitive](
        rule_context, *invals, **eqn.params
    )
  File "/home/ayx/jax/jax/_src/pallas/mosaic/lowering.py", line 1551, in _broadcast_to_lowering_rule
    raise RuntimeError(
    ...<2 lines>...
    )
RuntimeError: `broadcast_to` is a Triton-specific primitive. Please consider using `jnp.broadcast_to` instead.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ayx/jax/3.py", line 29, in <module>
    main()
  File "/home/ayx/jax/3.py", line 25, in main
    out = kernel(x)
  File "/home/ayx/.local/share/uv/python/cpython-3.13.0-linux-x86_64-gnu/lib/python3.13/contextlib.py", line 85, in inner
    return func(*args, **kwds)
  File "/home/ayx/jax/jax/_src/pallas/pallas_call.py", line 1844, in wrapped
    jaxpr, consts = _trace_kernel_to_jaxpr(
  File "/home/ayx/jax/jax/_src/pallas/pallas_call.py", line 1416, in _trace_kernel_to_jaxpr
    jaxpr, _, consts, () = pe.trace_to_jaxpr_dynamic(wrapped_kernel_fun,
  File "/home/ayx/jax/jax/_src/pallas/primitives.py", line 833, in wrap_with_transforms
    return f(*new_args)
  File "/home/ayx/jax/3.py", line 20, in kernel
    x = pl.load(x_ref, idx)
  File "/home/ayx/jax/jax/_src/pallas/primitives.py", line 650, in load
    x_ref, transforms = sp.get_ref_and_transforms(x_ref_or_view, idx, "load")
  File "/home/ayx/jax/jax/_src/state/indexing.py", line 240, in from_indices_shape
    sp.broadcast_to(i, int_indexer_shape) for i in int_indexers
jax._src.source_info_util.JaxStackTraceBeforeTransformation: jax._src.pallas.mosaic.lowering.LoweringException: RuntimeError: `broadcast_to` is a Triton-specific primitive. Please consider using `jnp.broadcast_to` instead.
Additional diagnostics: 
Failing jaxpr equation: a:i32[4,2] = broadcast_to[shape=(4, 2)] b

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ayx/jax/3.py", line 29, in <module>
    main()
    ~~~~^^
  File "/home/ayx/jax/3.py", line 25, in main
    out = kernel(x)
  File "/home/ayx/.local/share/uv/python/cpython-3.13.0-linux-x86_64-gnu/lib/python3.13/contextlib.py", line 85, in inner
    return func(*args, **kwds)
  File "/home/ayx/jax/jax/_src/pallas/pallas_call.py", line 1520, in _pallas_call_lowering
    return mlir.lower_per_platform(ctx, "pallas_call",
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
                                   dict(cpu=cpu_lowering,
                                   ^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
                                   interpret=interpret,
                                   ^^^^^^^^^^^^^^^^^^^^
                                   **params)
                                   ^^^^^^^^^
  File "/home/ayx/jax/jax/_src/pallas/pallas_call.py", line 1493, in tpu_lowering
    return mosaic_tpu_backend.pallas_call_tpu_lowering_rule(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        ctx, *in_nodes, **params
        ^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/ayx/jax/jax/_src/pallas/mosaic/pallas_call_registration.py", line 147, in pallas_call_tpu_lowering_rule
    mosaic_module, extra_args = lower_module(for_verification=False)
                                ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ayx/jax/jax/_src/pallas/mosaic/pallas_call_registration.py", line 142, in lower_module
    return lowering.lower_jaxpr_to_module(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        ctx, mlir_ctx, grid_mapping, jaxpr,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        dimension_semantics=dimension_semantics, mesh=mesh,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        for_verification=for_verification,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        name_and_src_info=name_and_src_info)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ayx/jax/jax/_src/pallas/mosaic/lowering.py", line 550, in lower_jaxpr_to_module
    func_op = lower_jaxpr_to_func(
        ctx, jaxpr, mosaic_grid_mapping=mosaic_grid_mapping,
        name="main", for_verification=for_verification,
    )
  File "/home/ayx/jax/jax/_src/pallas/mosaic/lowering.py", line 730, in lower_jaxpr_to_func
    body = func.FuncOp.from_py_func(*arg_types, name=name)(body_func)
  File "/home/ayx/venv313/lib/python3.13/site-packages/jaxlib/mlir/dialects/func.py", line 195, in decorator
    return_values = f(*func_args, **func_kwargs)
  File "/home/ayx/jax/jax/_src/pallas/mosaic/lowering.py", line 726, in body_func
    return jaxpr_subcomp(
        lowering_context, jaxpr, *scalar_prefetch, *operands_and_scratch
    )
  File "/home/ayx/jax/jax/_src/pallas/mosaic/lowering.py", line 858, in jaxpr_subcomp
    raise new_error from e
  File "/home/ayx/jax/3.py", line 29, in <module>
    main()
  File "/home/ayx/jax/3.py", line 25, in main
    out = kernel(x)
  File "/home/ayx/.local/share/uv/python/cpython-3.13.0-linux-x86_64-gnu/lib/python3.13/contextlib.py", line 85, in inner
    return func(*args, **kwds)
  File "/home/ayx/jax/jax/_src/pallas/pallas_call.py", line 1844, in wrapped
    jaxpr, consts = _trace_kernel_to_jaxpr(
  File "/home/ayx/jax/jax/_src/pallas/pallas_call.py", line 1416, in _trace_kernel_to_jaxpr
    jaxpr, _, consts, () = pe.trace_to_jaxpr_dynamic(wrapped_kernel_fun,
  File "/home/ayx/jax/jax/_src/pallas/primitives.py", line 833, in wrap_with_transforms
    return f(*new_args)
  File "/home/ayx/jax/3.py", line 20, in kernel
    x = pl.load(x_ref, idx)
  File "/home/ayx/jax/jax/_src/pallas/primitives.py", line 650, in load
    x_ref, transforms = sp.get_ref_and_transforms(x_ref_or_view, idx, "load")
  File "/home/ayx/jax/jax/_src/state/indexing.py", line 240, in from_indices_shape
    sp.broadcast_to(i, int_indexer_shape) for i in int_indexers
jax._src.pallas.mosaic.lowering.LoweringException: RuntimeError: `broadcast_to` is a Triton-specific primitive. Please consider using `jnp.broadcast_to` instead.
Additional diagnostics: 
Failing jaxpr equation: a:i32[4,2] = broadcast_to[shape=(4, 2)] b

--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```

Note that the code works when running with `interpret=True`.

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.36.dev20241203+a54319ec1
jaxlib: 0.4.35
numpy:  2.1.2
python: 3.13.0 (main, Oct  8 2024, 01:04:00) [Clang 18.1.8 ]
device info: TPU v5 lite-8, 8 local devices"
process_count: 1
platform: uname_result(system='Linux', node='t1v-n-ab2ce832-w-0', release='5.19.0-1027-gcp', version='#29~22.04.1-Ubuntu SMP Thu Jun 22 05:13:17 UTC 2023', machine='x86_64')
```

**Comment by Imraj-Singh** [comment]
Hi @ayaka14732 , this is a problem I am running into, is there a work around? In my use case setting `interpret=True` does not resolve the problem. FYI the pallas kernel does work on the gpu (after a rather lengthy compliation). Any help would be appreciated, thanks!
