### ISSUE TITLE
Regressions in `debug_nans` (and `debug_infs`)

### ISSUE THREAD

**Issue by emilyfertig** [jax-ml/jax#25299]
### Description

The following code with `debug_nans`:

```
@jax.jit
def f(x):
  y = jnp.square(x)
  return jnp.log(-y)

with jax.debug_nans(True):
  x = jnp.array([2., 0.])
  f(x)
```
raises this error:

```
Traceback (most recent call last):
  File "/usr/local/google/home/emilyaf/jax-fork/jax/jax/_src/pjit.py", line 1699, in _pjit_call_impl_python
    return compiled.unsafe_call(*args), compiled, pgle_profiler
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/emilyaf/jax-fork/jax/jax/_src/profiler.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/emilyaf/jax-fork/jax/jax/_src/interpreters/pxla.py", line 1303, in __call__
    dispatch.check_special(self.name, arrays)
  File "/usr/local/google/home/emilyaf/jax-fork/jax/jax/_src/dispatch.py", line 316, in check_special
    _check_special(name, buf.dtype, buf)
  File "/usr/local/google/home/emilyaf/jax-fork/jax/jax/_src/dispatch.py", line 321, in _check_special
    raise FloatingPointError(f"invalid value (nan) encountered in {name}")
FloatingPointError: invalid value (nan) encountered in jit(f)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/google/home/emilyaf/jax-fork/jax/debug_nans_test.py", line 27, in <module>
    f(x)
FloatingPointError: invalid value (nan) encountered in jit(f). Because jax_config.debug_nans.value and/or config.jax_debug_infs is set, the de-optimized function (i.e., the function as if the jit decorator were removed) was called in an attempt to get a more precise error message. However, the de-optimized function did not produce invalid values during its execution. This behavior can result from jit optimizations causing the invalid value to be produced. It may also arise from having nan/inf constants as outputs, like jax.jit(lambda ...: jax.numpy.nan)(...). 

It may be possible to avoid the invalid value by removing the jit decorator, at the cost of losing optimizations. 

If you see this error, consider opening a bug report at https://github.com/jax-ml/jax.
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```

There are two issues:
1.) The message says "`...the de-optimized function did not produce invalid values during its execution...`". This is wrong -- `f` without `jit` also returns NaNs since it's taking the log of something negative (when the input is nonzero). This is consistently reproducible for different NaN-producing functions (this started after the jit/pjit merge).
2.) The traceback doesn't indicate the op in the user code that produced the NaN -- it should, and the docs say it does. (This appears to have been caused by 32bf19a, a few weeks ago.)

We should fix these, and improve `debug_nans` so that tracebacks give more helpful info (and less unhelpful info, i.e. paths through JAX internals), for the backward pass as well.

### System info (python version, jaxlib version, accelerator, etc.)

...

**Comment by emilyfertig** [comment]
Closed by #25519 . Further improvements are tracked in #25643
