### ISSUE TITLE
id_tap on CPU crashes with exceptions

### ISSUE THREAD

**Issue by sbodenstein** [jax-ml/jax#7439]
This crashes a CPU kernel, but prints the exception on a GPU/TPU kernel:
```
from jax.experimental import host_callback  
import jax

def callback(val, transform):
  raise RuntimeError('Error!')

try:
  host_callback.id_tap(callback, 1.2)
  host_callback.barrier_wait()
except jax.experimental.host_callback.CallbackException as e:
  print(e)
  ```

**Comment by zhangqiaorjc** [comment]
seems like a regression, jaxlib 0.1.68 produces the exception

```
ERROR:absl:Outside call <function _call.<locals>.<lambda> at 0x7f04e2fd2dd0> threw exception Error!.
ERROR:absl:Postponing exception raised in callback function: Traceback (most recent call last):
  File "/usr/local/google/home/zhangqiaorjc/repos/jax/jax/experimental/host_callback.py", line 1747, in _callback_input_received
    return callback(arrays, device)
  File "/usr/local/google/home/zhangqiaorjc/repos/jax/jax/experimental/host_callback.py", line 1156, in _outside_call_run_callback
    raise e  # Let the exception propagate
  File "/usr/local/google/home/zhangqiaorjc/repos/jax/jax/experimental/host_callback.py", line 1099, in _outside_call_run_callback
    res = callback(arg, device, unpacked_transforms)
  File "/usr/local/google/home/zhangqiaorjc/repos/jax/jax/experimental/host_callback.py", line 689, in <lambda>
    callback = lambda arg, device, transforms: callback_func(arg, transforms)
  File "hcb_repro.py", line 5, in callback
    raise RuntimeError('Error!')
RuntimeError: Error!

There were exceptions during callback processing. Last one was: Traceback (most recent call last):
  File "/usr/local/google/home/zhangqiaorjc/repos/jax/jax/experimental/host_callback.py", line 1747, in _callback_input_received
    return callback(arrays, device)
  File "/usr/local/google/home/zhangqiaorjc/repos/jax/jax/experimental/host_callback.py", line 1156, in _outside_call_run_callback
    raise e  # Let the exception propagate
  File "/usr/local/google/home/zhangqiaorjc/repos/jax/jax/experimental/host_callback.py", line 1099, in _outside_call_run_callback
    res = callback(arg, device, unpacked_transforms)
  File "/usr/local/google/home/zhangqiaorjc/repos/jax/jax/experimental/host_callback.py", line 689, in <lambda>
    callback = lambda arg, device, transforms: callback_func(arg, transforms)
  File "hcb_repro.py", line 5, in callback
    raise RuntimeError('Error!')
RuntimeError: Error!
```

But jaxlib 0.1.69 crashes

```
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
ERROR:absl:Outside call <function _call.<locals>.<lambda> at 0x7fab217f1dd0> threw exception Error!.
terminate called after throwing an instance of 'pybind11::error_already_set'
  what():  RuntimeError: Error!

At:
  hcb_repro.py(5): callback
  /usr/local/google/home/zhangqiaorjc/repos/jax/jax/experimental/host_callback.py(689): <lambda>
  /usr/local/google/home/zhangqiaorjc/repos/jax/jax/experimental/host_callback.py(1156): _outside_call_run_callback
  /usr/local/google/home/zhangqiaorjc/repos/jax/jax/experimental/host_callback.py(1025): wrapped_callback
  /usr/local/google/home/zhangqiaorjc/repos/jax/jax/interpreters/xla.py(893): _execute_compiled
  /usr/local/google/home/zhangqiaorjc/repos/jax/jax/interpreters/xla.py(249): apply_primitive
  /usr/local/google/home/zhangqiaorjc/repos/jax/jax/experimental/host_callback.py(911): _outside_call_impl
  /usr/local/google/home/zhangqiaorjc/repos/jax/jax/core.py(603): process_primitive
  /usr/local/google/home/zhangqiaorjc/repos/jax/jax/core.py(264): bind
  /usr/local/google/home/zhangqiaorjc/repos/jax/jax/experimental/host_callback.py(714): _call
  /usr/local/google/home/zhangqiaorjc/repos/jax/jax/experimental/host_callback.py(584): id_tap
  hcb_repro.py(8): <module>
```

**Comment by gnecula** [comment]
The issue comes from the fact that with ` jaxlib 0.1.68` the host_callback module on CPU uses a different implementation mechanism than on GPU and TPU: instead of outfeed it uses by default an XLA CustomCall. This will eventually be rolled out to GPU also, but not TPU. (You can force the use of outfeed even on CPU with `JAX_HOST_CALLBACK_OUTFEED=True`)

The proper solution is to get the XLA CustomCall to throw a proper Python exception, not crash. This should be possible.

**Comment by gnecula** [comment]
It seems that doing this depends on rolling out a [new feature for CustomCall](https://github.com/tensorflow/tensorflow/blob/ea0b101ff548d4c59bc83acc5adf4bff91a33184/tensorflow/compiler/xla/service/hlo.proto#L60-L63), to enable it to return a status.

**Comment by Edenhofer** [comment]
On jaxlib==0.1.73 I again get a `RuntimeError`. Did JAX by chance switch the host callback method because I don't think the CustomCall implementation in XLA was changed for the CPU (https://github.com/tensorflow/tensorflow/commits/master/tensorflow/compiler/xla/service/hlo.proto)?

Anyways, this bug might potentially be outdated.

**Comment by gnecula** [comment]
Nothing has changed on the host_callback side, but it seems that there were changes in the way XLA CustomCall handles exceptions. Now, instead of crashing the runtime the exception from the called Python function is propagated properly up the call stack. 

I think that this is a step in the right direction. However, the behavior is still slightly different depending on the JAX_HOST_CALLBACK_OUTFEED environment variable (default False on CPU and True on other platforms). If we use outfeed then the `CallbackException` error comes from `hcb.barrier_wait`, otherwise the actual exception comes directly from the `hcb.id_tap` function.

**Comment by hawkinsp** [comment]
id_tap has been removed from JAX, so this issue should be moot.
